### ISSUE TITLE
Warning "Animated: `useNativeDriver` was not specified" when interacting

### ISSUE THREAD

**Issue by bakkerjoeri** [repodio/react-native-scrubber#10]
When interacting with the scrubber, the Animated library in react-native will throw a warning:

> Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

Although not stated in the documentation of Animated, apparently the config of `Animated.timing` is also required to specify a value for `useNativeDriver`.

Found in version react-native-scrubber@1.1.4.

**Comment by CapitanRedBeard** [comment]
Fixed in version 1.1.5
