### ISSUE TITLE
What is the LICENSE for this repo?

### ISSUE THREAD

**Issue by rsml** [repodio/react-native-scrubber#27]
Please add a LICENSE file so I know whether it can be used in commercial projects. For instance MIT is a popular permissive license. Here's an example: [https://github.com/nick-michael/react-scrubber/blob/master/LICENSE](https://github.com/nick-michael/react-scrubber/blob/master/LICENSE)

**Comment by CapitanRedBeard** [comment]
MIT License https://github.com/repodio/react-native-scrubber/pull/36
