### ISSUE TITLE
Add tap to navigate support?

### ISSUE THREAD

**Issue by sjsakib** [repodio/react-native-scrubber#5]
Users might want to tap on a location to navigate there. Most media controls support this feature. Any plan to add this?

I'd like to implement this and make a PR, how should we do this? I'm thinking of using `TouchableWithoutFeedback` with an `onPress` handler for track container.

**Comment by CapitanRedBeard** [comment]
@sjsakib Playing with a couple iOS audio apps on my phone I can't actually find one that does this. So if you want to add this feature I would lobby for it to be off by default and enabled given a boolean prop.

Now that this module is written using [react-native-gesture-handler](https://software-mansion.github.io/react-native-gesture-handler/) my guess is you could wrap the entire track in a [TapGestureHandler](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-tap.html) and on the `onHandlerStateChange` callback you could check where along the X axis the it was pressed and set the new position accordingly. 

You might need to set it up so it only fires on a press out so it doesn't conflict with the already existing [PanGestureHandler](https://github.com/repodio/react-native-scrubber/blob/master/index.js#L323) that handles the panning.

The tricky part will definitely be getting this to work without messing up the existing PanGestureHandler, if there is a will there is a way.

**Comment by CapitanRedBeard** [comment]
#6
